apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/italoag/onchain-dev-stack'
    path: vault/argocd/vault-ingress
    helm:
      valueFiles:
        - environments/values-dev.yaml
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
