apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-ingress
  namespace: argocd
  labels:
    app.kubernetes.io/name: firefly-ingress
    app.kubernetes.io/part-of: firefly
spec:
  project: default
  source:
    repoURL: https://github.com/italoag/onchain-dev-stack.git
    targetRevision: main
    path: firefly/argocd
    directory:
      include: "values/ingress.yaml"
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 10