apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firefly-ingress
  namespace: firefly
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-certmanager"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - firefly.cluster.eita.cloud
    secretName: firefly-tls  # Esse secret será criado automaticamente pelo cert-manager
  rules:
  - host: firefly.cluster.eita.cloud
    http:
      paths:
        # Regra para servir a API FireFly Core (HTTP)
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: firefly
              port:
                number: 5000
        # Regra para servir a UI FireFly Core (HTTP)
        - path: /ui
          pathType: Prefix
          backend:
            service:
              name: firefly
              port:
                number: 5000
        # Regra para servir métricas (Prometheus)
        - path: /metrics
          pathType: Prefix
          backend:
            service:
              name: firefly
              port:
                number: 5100
